// Картинки вещей рюкзака — пиксельные карты, как у рыб (FISH в shared/src/fish.ts): буква — цвет из pal, точка — пусто.
// Каждая нарисована 1:1 в арт-пикселях под свой размер в клетках (клетка 24×24): удочка и невод 4×1 — до 96×24,
// лодка и накидка 2×2 — до 48×48, сачок 2×1 — до 48×24, мелочь — до 24×24. В клетках рисуются по центру; повёрнутая
// вещь — та же картинка, повёрнутая на четверть оборота по часовой.

import type { ItemKind } from '@fh/shared';

export interface ItemArt { pal: Record<string, string>; map: string[] }

export const ITEM_ART: Record<ItemKind, ItemArt> = {
  'rod-willow': {
    pal: { C: 'ecd585', E: '8a9a3c', U: '8a7a3c', e: '4c6b2a', g: '5b7381', h: 'b5b9b8', k: '432115', l: 'e4e8e4', n: 'aab65a', o: '240702', r: 'c9532d', t: 'f4e3c1', u: '5a4a20', w: 'c98a4b' },
    map: [
      '...................................................oo.......................................',
      '.oooooooooooooooooooo.............................oneo......................................',
      'okUUwCwCUUUUUCwCwUUUUoooooooooooooooooooooooooooooneoooooooooooooooooooooooooooooooooooooo..',
      'okuUCwCwUUUUuwCwCuUUUgEEEEEEEEEuEEEEEEEEEEEEEuEEEEEEEEEEEUUUUUUUuUUUUUUUUUUUUUuUUUUUUUUUUUo.',
      'okUUwCwCUuUUUCwCwUUuUgUUUUUUUUUuUUUUUUUUUUUUUuUUUUUUUUUUUoooooooooooooooooooooooooooooooool.',
      '.oooooooooooooooooooooooooooooooooooooooooooooooooooooooo.................................l.',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '.........................................................................................oro',
      '.........................................................................................oro',
      '.........................................................................................oto',
      '.........................................................................................oto',
      '.........................................................................................oko',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '........................................................................................h.h.',
      '.........................................................................................hh.',
    ],
  },
  'rod-bamboo': {
    pal: { G: 'f8c12a', R: '8e3220', Y: 'a8862e', c: 'd2a03a', g: '5b7381', h: 'b5b9b8', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d', x: '1c1a20', y: 'd9c36a' },
    map: [
      '.oooooooooooooooooooo.o........o........o........o..........................................',
      'okRrRrRrRrRrRrRrRrRrRoYooooooooYooooooooYooooooooYoooooooooooooooooooooooooooooooooooooooo..',
      'okRrRrRrRrRrRrRrRrRrRgYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyYo.',
      'okRrRrRrRrRrRrRrRrRrRgYccccccccYccccccccYccccccccYcccccccoooooooooooooooooooooooooooooooool.',
      '.oooooooooooooooooooooYooooooooYooooooooYooooooooYooooooo.................................l.',
      '......................o........o........o........o........................................l.',
      '..........................................................................................l.',
      '.........................................................................................oGo',
      '.........................................................................................oGo',
      '.........................................................................................oxo',
      '.........................................................................................oxo',
      '.........................................................................................oko',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '........................................................................................h.h.',
      '.........................................................................................hh.',
    ],
  },
  'rod-tele': {
    pal: { B: '3f6f9a', S: 'e4e8e4', X: '3a3a44', b: '2f4c6e', g: '5b7381', h: 'b5b9b8', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d', s: 'b5b9b8', x: '1c1a20', z: '6a6a78' },
    map: [
      '.oooooooooooooooooooo.......................o...............................................',
      'okzzzzxzzzxzzzxzzzzzzooooooooooooooooooooooosooooooooooooooooooooooooooooooooooooooooooooo..',
      'okXXXXxXXXxXXXxXXXXXXgBBBBBBBBBBBBBBBBBBBBBBssBBBBBBBBBBBBBBBBBBBssBBBBBBBBBBBBBBBBBBBBBBro.',
      'okXXXXxXXXxXXXxXXXXXXgbbbbbbbbbbbbbbbbbbbbbbssbbbbbbbbbbbooooooooooooooosooooooooooosoooool.',
      '.oooooooooooooooooooooooogoooooooooooosooooosooooooooosoo...............o...........o.....l.',
      '.......................oosoo..........o.....o.........o...................................l.',
      '......................ossssso.............................................................l.',
      '......................ossssso............................................................oro',
      '......................ossgssoo...........................................................oro',
      '......................osssssoXo..........................................................oSo',
      '.......................ossso.o...........................................................oSo',
      '........................ooo..............................................................oko',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '........................................................................................h.h.',
      '.........................................................................................hh.',
    ],
  },
  'rod-carbon': {
    pal: { C: 'ecd585', G: 'f8c12a', S: 'e4e8e4', X: '3a3a44', c: 'd2a03a', g: '5b7381', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d', s: 'b5b9b8', w: 'c98a4b', x: '1c1a20', z: '6a6a78' },
    map: [
      '.oooooooooooooooooooo........................................................................',
      'okwCCCCCCwCCCCCCwXXXXooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...',
      'okcccwccccccwccccXXXXgzzzzzzzzzzzzzzGGzzzzzzzzzzzzGGzzzzzXXXXXXXGXXXXXXXXXXXXGXXXXXXXXXXXGo..',
      'okccccccwccccccwcXXXXgxxxxxxxxxxxxxxGGxxxxxxxxxxxxGGxxxxxooooooosoooooooooooosooooooooooool..',
      '.ooooooooooooooooooooooooogooooooooosooooooooooooosoooooo.......o............o............l..',
      '........................ooooo.......o.............o.......................................l..',
      '.......................oSSSSSo............................................................l..',
      '......................oSSSSSSSo...........................................................l..',
      '......................oSSSgSSSo...........................................................l..',
      '......................oSSSSSSSxo..........................................................l..',
      '......................oSSSSSSSo...........................................................l..',
      '.......................oSSSSSo...........................................................oSo.',
      '........................ooooo............................................................osSo',
      '.........................................................................................orso',
      '..........................................................................................oo.',
    ],
  },
  'rod-gold': {
    pal: { D: '7a3d20', F: 'c27709', G: 'f8c12a', H: 'fff6d8', d: '642d18', f: 'f08a1c', g: '5b7381', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d' },
    map: [
      '.oooooooooooooooooooo.........................................................................',
      'okDGDDDDGDDDDGDDDDGDDooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....',
      'okdGddddGddddGddddGddgHHHHHHFHHHHHHHHHHHHHFHHHHHHHHHHHHHFGGGGGGGGGGGGGFGGGGGGGGGGGFGGGGGGHo...',
      'okdGddddGddddGddddGddgGGGGGGFGGGGGGGGGGGGGFGGGGGGGGGGGGGFoooooooooGoooooooooooGoooooooooool...',
      '.ooooooooooooooooooooooooogoooooooooooGoooooooooooooGoooo.........o...........o...........l...',
      '........................ooooo.........o.............o.....................................l...',
      '.......................oGGGGGo............................................................l...',
      '......................oGGGGGGGo...........................................................l...',
      '......................oGGGrGGGo...........................................................l...',
      '......................oGGGGGGGFo..........................................................lo..',
      '......................oGGGGGGGo..........................................................oGfo.',
      '.......................oGGGGGo..........................................................oHfGFo',
      '........................ooooo............................................................oGoo.',
      '..........................................................................................o...',
    ],
  },
  'boat-raft': {
    pal: { C: 'ecd585', D: '7a3d20', M: 'b16f38', R: '8e3220', c: 'd2a03a', m: '975220', o: '240702', r: 'c9532d', w: 'c98a4b' },
    map: [
      '....................oo....................',
      '...................owmo...................',
      '...................owmrooo................',
      '...................owmrrrroo..............',
      '...................owmrrrrrrooo...........',
      '...................owmrrrrrrrrro..........',
      '...................owmrrrrrrrrro..........',
      '...................owmRRRRRRooo...........',
      '...................owmRRRRoo..............',
      '...................owmRooo................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...................owmo...................',
      '...ooooooooooooooooowmooooooooooooooooo...',
      '..owwwwwccwwwwwwwwwwwwwwwwwwwwwwccwwwwwo..',
      '.oMMMMMMCMMMMMMMMMMMMMMMMMMMMMMMCMMMMMMMo.',
      '.oMCMMMMMcMMMMMMMMMMMMMMMMMMMMMMMcMMMMCMo.',
      '.ommmmmmCCmmmmmmmmmmmmmmmmmmmmmmCCmmmmmmo.',
      '..oDDDDDcDDDDDDDDDDDDDDDDDDDDDDDcDDDDDDo..',
      '.owwwwwwwCwwwwwwwwwwwwwwwwwwwwwwwCwwwwwwo.',
      'oMMMMMMMccMMMMMMMMMMMMMMMMMMMMMMccMMMMMMMo',
      'oMCMMMMMCMMMMMMMMMMMMMMMMMMMMMMMCMMMMMMCMo',
      'ommmmmmmmcmmmmmmmmmmmmmmmmmmmmmmmcmmmmmmmo',
      '.oDDDDDDCCDDDDDDDDDDDDDDDDDDDDDDCCDDDDDDo.',
      '..owwwwwcwwwwwwwwwwwwwwwwwwwwwwwcwwwwwwo..',
      '.oMMMMMMMCMMMMMMMMMMMMMMMMMMMMMMMCMMMMMMo.',
      '.oMCMMMMccMMMMMMMMMMMMMMMMMMMMMMccMMMMCMo.',
      '.ommmmmmCmmmmmmmmmmmmmmmmmmmmmmmCmmmmmmmo.',
      '..oDDDDDDcDDDDDDDDDDDDDDDDDDDDDDDcDDDDDo..',
      '.owwwwwwCCwwwwwwwwwwwwwwwwwwwwwwCCwwwwwwo.',
      'oMMMMMMMcMMMMMMMMMMMMMMMMMMMMMMMcMMMMMMMMo',
      'oMCMMMMMMCMMMMMMMMMMMMMMMMMMMMMMMCMMMMMCMo',
      'ommmmmmmccmmmmmmmmmmmmmmmmmmmmmmccmmmmmmmo',
      '.oDDDDDDCDDDDDDDDDDDDDDDDDDDDDDDCDDDDDDDo.',
      '..oooooooooooooooooooooooooooooooooooooo..',
    ],
  },
  'boat-rubber': {
    pal: { F: 'c27709', G: 'f8c12a', H: 'fff6d8', M: 'b16f38', R: '8e3220', f: 'f08a1c', k: '432115', o: '240702', r: 'c9532d', w: 'c98a4b' },
    map: [
      '................................ooo.......',
      '...............................oGGGo......',
      '...............................oGGGo......',
      '...............................oGHGo......',
      '..............................oGGGGGo.....',
      '..............................oGGGGGo.....',
      '..............................oGGGGGo.....',
      '..............................owGGGo......',
      '.............................owMGGGo......',
      '............................owMoGGGo......',
      '............................owMoooo.......',
      '...........................owMo...........',
      '..........................owMo............',
      '.........................owMo.............',
      '........................owMo..............',
      '........................owMo..............',
      '.......................owMo...............',
      '......................owMo................',
      '.....................owMo.................',
      '....................owMo..................',
      '....................owMo..................',
      '.......ooooooooooooowMooooooooooooo.......',
      '....oooGGGGGGGGGGGGGGGGGGGGGGGGGGGGooo....',
      '..ooGrGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGrGoo..',
      '.offfrfffHHHffffffffffffffffffffffffrfffo.',
      '.offfrfffffkffffffkffffffkffffffkfffrfffo.',
      'offffrfRRRRkRRRRRRkRRRRRRkRRRRRRkRRfrffffo',
      'offffrffffffffffffffffffffffffffffffrffffo',
      'offffrffffffffffffffffffffffffffffffrffffo',
      'offffrffffffffffffffffffffffffffffffrffffo',
      'oFFFFrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrFFFFo',
      'oFFFFrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrFFFFo',
      '.oFFFrFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrFFFo.',
      '.oRRRrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrRRRo.',
      '..ooRrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrRoo..',
      '....oooRRRRRRRRRRRRRRRRRRRRRRRRRRRRooo....',
      '.......owMooooooooooooooooooooooooo.......',
      '......owMo................................',
      '.......oo.................................',
    ],
  },
  'boat-row': {
    pal: { D: '7a3d20', M: 'b16f38', c: 'd2a03a', k: '432115', m: '975220', o: '240702', s: 'b5b9b8', w: 'c98a4b' },
    map: [
      '...o........................................',
      '..oMo.......................................',
      '.oMMMo......................................',
      'oMwMMMo.....................................',
      'oMMMMMo.....................................',
      'oMMMMMo.....................................',
      'oMMMMMo.....................................',
      'oMMMMMMo....................................',
      '.oMMMowMo...................................',
      '..oMo.owMo..................................',
      '...o...owMo.................................',
      '.......owMo.................................',
      '........owMo................................',
      '.........owMo...............................',
      '..........owMo..............................',
      '...........owMo.............................',
      '............owMo............................',
      '.............owMo.........................o.',
      '..............owMo.......................owo',
      '...............owMo....................oowco',
      '...............owMo...................owwcMo',
      '................owMo.................owccmmo',
      '.................owMoo.............oowcmmmo.',
      '.oooooooooooooooooowssooooooooooooowwcmmmDo.',
      'owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwccMMMDo..',
      'occccccccccccccccccccccccccccccccccMMMMMo...',
      'oDMMMMMMkMMMMMMMMMMMkMMMMMMMMMMMkMMMMMMDo...',
      'oDmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmDo....',
      'oDmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmo.....',
      'oDmmmmmmkmmmmmmmmmmmkmmmmmmmmmmmkmmmmDo.....',
      '.oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo......',
      '.oDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDo......',
      '..oDMMMMkMMMMMMMMMMMkMMMMMMMMMMMkMMDo.......',
      '...ommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmo........',
      '...oDmmmmmmmmmmmmmmmmmmmmmmmmmmmmmDo........',
      '....oDmmkmmmmmmmmmmmkmmmmmmmmmmmkDo.........',
      '.....oMMMMMMMMMMMMMMMMMMMMMMMMMMMo..........',
      '.....oDDDDDDDDDDDDDDDDDDDDDDDDDDDo..........',
      '......ooooooooooooooooooooooooooo...........',
    ],
  },
  'boat-canoe': {
    pal: { C: 'ecd585', M: 'b16f38', R: '8e3220', k: '432115', o: '240702', r: 'c9532d', t: 'f4e3c1', w: 'c98a4b' },
    map: [
      '...........o..................................',
      '..........owo.................................',
      '.........owwwo................................',
      '........owCwwwo...............................',
      '........owwwwwo...............................',
      '........owwwwwo...............................',
      '........owwwwwo...............................',
      '........owwwwwo...............................',
      '.........owwwMwo..............................',
      '..........owoMwo..............................',
      '...........o.oMwo.............................',
      '..............oMwo............................',
      '...............oMwo...........................',
      '...............oMwo...........................',
      '................oMwo..........................',
      '.................oMwo.........................',
      '.................oMwo.........................',
      '..................oMwo........................',
      '.o.................oMwo.....................o.',
      'oko.................oMwo...................oko',
      'oto.................oMwo...................oto',
      'orko.................oMwo.................okro',
      'ortko.................oMwo...............oktro',
      'orrtko................oMwo..............oktrro',
      'orrrtko................oMwo............oktrrro',
      'orrrrtkooooooooooooooooooMwooooooooooooktrrrro',
      '.orrrrtkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkktrrrro.',
      '..orrrrttttttttttttttttttttttttttttttttrrrro..',
      '...orrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrro...',
      '....orrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrro....',
      '.....orrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrro.....',
      '......orrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrro......',
      '.......oRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRo.......',
      '........oRRRRRRRRRRRRRRRRRRRRRRRRRRRRo........',
      '.........oRRRRRRRRRRRRRRRRRRRRRRRRRRo.........',
      '..........oooooooooooooooooooooooooo..........',
    ],
  },
  'boat-motor': {
    pal: { B: '3f6f9a', H: 'fff6d8', S: 'e4e8e4', X: '3a3a44', a: '94d6f1', b: '2f4c6e', o: '240702', r: 'c9532d', s: 'b5b9b8', z: '6a6a78' },
    map: [
      '.oooooo.......................................',
      'orrrrrro.................ooooo................',
      'orrrrrro................oSSSSSo...............',
      'oXXXXXXo................oaaaaSo...............',
      'oXzXXXXo...............oaHaaaSo...............',
      'oXzXXXXo..........ooo..oHaaaaSo............oo.',
      'oXXXXXXo.........oXXXooaaaaaaSo..........ooSSo',
      'oXXXXXXo..........oXo.oaaaaaaSo.......oooSSSSo',
      'oXXXXXXo..........oXooaaaaaaaSo.....ooSSSssSSo',
      'oXXXXXXooooooooooooXooaaaaaaaSooooooSSsssSSSSo',
      '.ooXXooSSSSSSSSSSSSSSSSSSSSSSSSSSSSSssSSSSSSo.',
      '..oXXooSssssssssssssssssssssssssssssSSSSSSSo..',
      '..oXXooSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSoo...',
      '..oXXooSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo.....',
      '..oXXooSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo......',
      '..oXXooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoo.......',
      '..oXXooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBo.........',
      '..oXXooSSSSSSSSSSSSSSSSSSSSSSSSSSSSo..........',
      '..oXXoobbbbbbbbbbbbbbbbbbbbbbbbbboo...........',
      '..oXXoobbbbbbbbbbbbbbbbbbbbbbbbbo.............',
      '..oXXoobbbbbbbbbbbbbbbbbbbbbbbbo..............',
      '..oXXoobbbbbbbbbbbbbbbbbbbbbboo...............',
      '.ooXXo.oooooooooooooooooooooo.................',
      'ossssso.......................................',
      'ossssso.......................................',
      '.oosoo........................................',
      '...o..........................................',
    ],
  },
  'net-scoop': {
    pal: { M: 'b16f38', S: 'e4e8e4', k: '432115', o: '240702', q: 'ecd585', s: 'b5b9b8', w: 'c98a4b' },
    map: [
      '.................................o..........',
      '.............................oooosoooo......',
      '............................ossssqsssso.....',
      '..........................oosoooq.ooqosoo...',
      '.........................osSoq.q.q.q.qosso..',
      '.........................oso..q...q...qoso..',
      '........................osSq.q.q.q.q.q.qoso.',
      '.oooooooooooooooooooooo.oso.q...q...q...qso.',
      'okkkkwwwwwwwwwwwwwwwwwwoosoq.q.q.q.q.q.qoso.',
      'okkkkMMMMMMMMMMMMMMMMMMosoq...q...q...q..oso',
      '.oooooooooooooooooooooo.osoq.q.q.q.q.q.qoso.',
      '........................oso.q...q...q...qso.',
      '........................osoq.q.q.q.q.q.qoso.',
      '.........................oso..q...q...qoso..',
      '.........................ossoq.q.q.q.qosso..',
      '..........................oosoooq.ooqosoo...',
      '............................ossssqsssso.....',
      '.............................oooosoooo......',
      '.................................o..........',
    ],
  },
  'net-cast': {
    pal: { C: 'ecd585', Y: 'a8862e', g: '5b7381', o: '240702', q: 'ecd585', s: 'b5b9b8' },
    map: [
      '........................o.......................',
      '......................ooCoo.....................',
      '.....................oCCoCCo....................',
      '.....................oCo.oCo....................',
      '....................oCo...oCo...................',
      '.....................oCo.oCo....................',
      '.....................oCCoCCo....................',
      '.....................oooCooo....................',
      '....................oYYYCYYYo...................',
      '...................oYqoooooqYo..................',
      '...................oYoq...qoYo..................',
      '..................oYo..q.q..oYo.................',
      '..................oYo...q...oYo.................',
      '.................oYq...q.q...qYo................',
      '................oYo.q.q...q.q.oYo...............',
      '................oYo..q.....q..oYo...............',
      '...............oYo..q.q...q.q..oYo..............',
      '..............oYoq.q...q.q...q.qoYo.............',
      '..............oYo.q.....q.....q.oYo.............',
      '.............oYo.q.q...q.q...q.q.oYo............',
      '.............oYoq...q.q...q.q...qoYo............',
      '............oYoq.....q.....q.....qoYo...........',
      '...........oYoq.q...q.q...q.q...q.qoYo..........',
      '...........oYq...q.q...q.q...q.q...qYo..........',
      '..........oYq.....q.....q.....q.....qYo.........',
      '.........oYq.q...q.q...q.q...q.q...q.qYo........',
      '.........oYo..q.q...q.q...q.q...q.q..oYo........',
      '........oYo....q.....q.....q.....q....oYo.......',
      '........oYq...q.q...q.q...q.q...q.q...qYo.......',
      '.......oYo.q.q...q.q...q.q...q.q...q.q.oYo......',
      '......oYo...q.....q.....q.....q.....q...oYo.....',
      '......oYo..q.q...q.q...q.q...q.q...q.q..oYo.....',
      '.....oYoq.q...q.q...q.q...q.q...q.q...q.qoYo....',
      '.....oYo.q.....q.....q.....q.....q.....q..oYo...',
      '....oYo.q.q...q.q...q.q...q.q...q.q...q.q.oYo...',
      '...oYq.q...q.q...q.q...q.q...q.q...q.q...q.qYo..',
      '...oYoq.....q.....q.....q.....q.....q.....qoYo..',
      '..oYoq.q...q.q...q.q...q.q...q.q...q.q...q.qoYo.',
      '.oYoq...q.q...q.q...q.q...q.q...q.q...q.q...qoYo',
      '.oYqoooooqoooooqoooooqoooooqoooooqoooooqoooooqYo',
      'oYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
      '.osgooosgooosgooosgooosgooosgooosgooosgooosgoooo',
      '.oggo.oggo.oggo.oggo.oggo.oggo.oggo.oggo.oggo...',
      '..oo...oo...oo...oo...oo...oo...oo...oo...oo....',
    ],
  },
  'net-seine': {
    pal: { G: 'f8c12a', M: 'b16f38', Y: 'a8862e', f: 'f08a1c', g: '5b7381', o: '240702', q: 'ecd585', s: 'b5b9b8', w: 'c98a4b' },
    map: [
      '.oo........................................................................................oo.',
      'owMo......................................................................................owMo',
      'owMo...ooooo......ooooo......ooooo......ooooo......ooooo......ooooo......ooooo............owMo',
      'owMoooofGfffoooooofGfffoooooofGfffoooooofGfffoooooofGfffoooooofGfffoooooofGfffooooooooooooowMo',
      'owMYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYYYYYYYYwMo',
      'owMooqofffffoooooqfffffqooooofffffoqoooofffffooqooofffffoooqoofffffooooqofffffoooooqoooooqowMo',
      'owMoq.qoooqoq...q.qoooq.q...qoqoooq.q...qoqoo.q.q..oqoqo..q.q.ooqoq...q.qoooqoq...q.q...q.owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMo....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q...owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMoq.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.owMo',
      'owMo.q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....qowMo',
      'owMoq.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMo....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q...owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMoq.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.owMo',
      'owMooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqowMo',
      'owMYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYwMo',
      'owMoooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoowMo',
      'owMo..oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggoowMo',
      '.oo....oo......oo......oo......oo......oo......oo......oo......oo......oo......oo......oo..oo.',
    ],
  },
  'worms': {
    pal: { C: 'ecd585', E: '8a9a3c', P: 'b85a6a', S: 'e4e8e4', X: '3a3a44', d: '642d18', e: '4c6b2a', g: '5b7381', k: '432115', o: '240702', p: 'e88a8a', s: 'b5b9b8' },
    map: [
      '...........o....',
      '......oo..oPo...',
      '.....oppo..opo..',
      '....opooPo.opo..',
      '....opo.o.opo...',
      '...oopoooopoo...',
      '..oddddddddddo..',
      '.okkkkkkkkkkkko.',
      'osssssssssssssso',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      'oeeeeeeeeeeeeeeo',
      'oEEEEEEEEEEEEEEo',
      'oEEEEECECECEEEEo',
      'oEEEEEEEEEEEEEEo',
      'oeeeeeeeeeeeeeeo',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      '.oooooooooooooo.',
    ],
  },
  'floats': {
    pal: { B: '3f6f9a', G: 'f8c12a', H: 'fff6d8', M: 'b16f38', a: '94d6f1', o: '240702', r: 'c9532d', t: 'f4e3c1' },
    map: [
      '..o..........',
      '.oro.........',
      '.oro.........',
      '.oro.....o...',
      '.oro....oGo..',
      '.orro...oGo..',
      'orrrro..oGo..',
      'orHrro..oGo..',
      'otttto..oBBo.',
      'otttto.oBBBBo',
      'otttto.oBaBBo',
      'otttto.otttto',
      'otttto.otttto',
      '.otto..otttto',
      '.oMo...otttto',
      '.oMo...otttto',
      '.oMo....otto.',
      '.oMo....oMo..',
      '..o.....oMo..',
      '........oMo..',
      '........oMo..',
      '.........o...',
    ],
  },
};

const sprites = new Map<string, HTMLCanvasElement>();
// Картинка вещи на отдельном холсте (собирается один раз); rot — повёрнутая.
export function itemSprite(kind: ItemKind, rot = false): HTMLCanvasElement {
  const key = kind + (rot ? '+' : '');
  let c = sprites.get(key);
  if (c) return c;
  const { pal, map } = ITEM_ART[kind], h = map.length, w = map[0]!.length;
  c = document.createElement('canvas');
  c.width = rot ? h : w; c.height = rot ? w : h;
  const x = c.getContext('2d')!, img = x.createImageData(c.width, c.height);
  for (let y = 0; y < h; y++) for (let i = 0; i < w; i++) {
    const ch = map[y]![i]!; if (ch === '.') continue;
    const hex = pal[ch] || 'ff00ff', px = rot ? h - 1 - y : i, py = rot ? i : y, o = (py * c.width + px) * 4;
    img.data[o] = parseInt(hex.slice(0, 2), 16); img.data[o + 1] = parseInt(hex.slice(2, 4), 16); img.data[o + 2] = parseInt(hex.slice(4, 6), 16); img.data[o + 3] = 255;
  }
  x.putImageData(img, 0, 0);
  sprites.set(key, c);
  return c;
}
