// Картинки вещей рюкзака — пиксельные карты, как у рыб (FISH в shared/src/fish.ts): буква — цвет из pal, точка — пусто.
// Каждая нарисована 1:1 в арт-пикселях под свой размер в клетках (клетка 24×24): удочка и невод 4×1 — до 96×24,
// накидка 2×2 — до 48×48, сачок и топор 2×1 — до 48×24, мелочь — до 24×24, ведро 4×4 — до 96×96 (его карту собрал скрипт
// по кругам и эллипсам — жестяное ведро с водой, как bucket.png, только крупнее). В клетках рисуются по центру; повёрнутая
// вещь — та же картинка, повёрнутая на четверть оборота по часовой. Рыба из ведра (fish, fish-fried) — 1×1, спрайтом своего вида.

import { FISH, ITEMS, type ItemKind } from '@fh/shared';

export interface ItemArt { pal: Record<string, string>; map: string[] }

export const ITEM_ART: Record<ItemKind, ItemArt> = {
  'rod-willow': {
    pal: { C: 'ecd585', E: '8a9a3c', U: '8a7a3c', e: '4c6b2a', g: '5b7381', h: 'b5b9b8', k: '432115', l: 'e4e8e4', n: 'aab65a', o: '240702', r: 'c9532d', t: 'f4e3c1', u: '5a4a20', w: 'c98a4b' },
    map: [
      '...................................................oo.......................................',
      '.oooooooooooooooooooo.............................oneo......................................',
      'okUUwCwCUUUUUCwCwUUUUoooooooooooooooooooooooooooooneoooooooooooooooooooooooooooooooooooooo..',
      'okuUCwCwUUUUuwCwCuUUUgEEEEEEEEEuEEEEEEEEEEEEEuEEEEEEEEEEEUUUUUUUuUUUUUUUUUUUUUuUUUUUUUUUUUo.',
      'okUUwCwCUuUUUCwCwUUuUgUUUUUUUUUuUUUUUUUUUUUUUuUUUUUUUUUUUoooooooooooooooooooooooooooooooool.',
      '.oooooooooooooooooooooooooooooooooooooooooooooooooooooooo.................................l.',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '.........................................................................................oro',
      '.........................................................................................oro',
      '.........................................................................................oto',
      '.........................................................................................oto',
      '.........................................................................................oko',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '........................................................................................h.h.',
      '.........................................................................................hh.',
    ],
  },
  'rod-bamboo': {
    pal: { G: 'f8c12a', R: '8e3220', Y: 'a8862e', c: 'd2a03a', g: '5b7381', h: 'b5b9b8', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d', x: '1c1a20', y: 'd9c36a' },
    map: [
      '.oooooooooooooooooooo.o........o........o........o..........................................',
      'okRrRrRrRrRrRrRrRrRrRoYooooooooYooooooooYooooooooYoooooooooooooooooooooooooooooooooooooooo..',
      'okRrRrRrRrRrRrRrRrRrRgYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyyyyyyYyyyYo.',
      'okRrRrRrRrRrRrRrRrRrRgYccccccccYccccccccYccccccccYcccccccoooooooooooooooooooooooooooooooool.',
      '.oooooooooooooooooooooYooooooooYooooooooYooooooooYooooooo.................................l.',
      '......................o........o........o........o........................................l.',
      '..........................................................................................l.',
      '.........................................................................................oGo',
      '.........................................................................................oGo',
      '.........................................................................................oxo',
      '.........................................................................................oxo',
      '.........................................................................................oko',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '........................................................................................h.h.',
      '.........................................................................................hh.',
    ],
  },
  'rod-tele': {
    pal: { B: '3f6f9a', S: 'e4e8e4', X: '3a3a44', b: '2f4c6e', g: '5b7381', h: 'b5b9b8', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d', s: 'b5b9b8', x: '1c1a20', z: '6a6a78' },
    map: [
      '.oooooooooooooooooooo.......................o...............................................',
      'okzzzzxzzzxzzzxzzzzzzooooooooooooooooooooooosooooooooooooooooooooooooooooooooooooooooooooo..',
      'okXXXXxXXXxXXXxXXXXXXgBBBBBBBBBBBBBBBBBBBBBBssBBBBBBBBBBBBBBBBBBBssBBBBBBBBBBBBBBBBBBBBBBro.',
      'okXXXXxXXXxXXXxXXXXXXgbbbbbbbbbbbbbbbbbbbbbbssbbbbbbbbbbbooooooooooooooosooooooooooosoooool.',
      '.oooooooooooooooooooooooogoooooooooooosooooosooooooooosoo...............o...........o.....l.',
      '.......................oosoo..........o.....o.........o...................................l.',
      '......................ossssso.............................................................l.',
      '......................ossssso............................................................oro',
      '......................ossgssoo...........................................................oro',
      '......................osssssoXo..........................................................oSo',
      '.......................ossso.o...........................................................oSo',
      '........................ooo..............................................................oko',
      '..........................................................................................l.',
      '..........................................................................................l.',
      '........................................................................................h.h.',
      '.........................................................................................hh.',
    ],
  },
  'rod-carbon': {
    pal: { C: 'ecd585', G: 'f8c12a', S: 'e4e8e4', X: '3a3a44', c: 'd2a03a', g: '5b7381', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d', s: 'b5b9b8', w: 'c98a4b', x: '1c1a20', z: '6a6a78' },
    map: [
      '.oooooooooooooooooooo........................................................................',
      'okwCCCCCCwCCCCCCwXXXXooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...',
      'okcccwccccccwccccXXXXgzzzzzzzzzzzzzzGGzzzzzzzzzzzzGGzzzzzXXXXXXXGXXXXXXXXXXXXGXXXXXXXXXXXGo..',
      'okccccccwccccccwcXXXXgxxxxxxxxxxxxxxGGxxxxxxxxxxxxGGxxxxxooooooosoooooooooooosooooooooooool..',
      '.ooooooooooooooooooooooooogooooooooosooooooooooooosoooooo.......o............o............l..',
      '........................ooooo.......o.............o.......................................l..',
      '.......................oSSSSSo............................................................l..',
      '......................oSSSSSSSo...........................................................l..',
      '......................oSSSgSSSo...........................................................l..',
      '......................oSSSSSSSxo..........................................................l..',
      '......................oSSSSSSSo...........................................................l..',
      '.......................oSSSSSo...........................................................oSo.',
      '........................ooooo............................................................osSo',
      '.........................................................................................orso',
      '..........................................................................................oo.',
    ],
  },
  'rod-gold': {
    pal: { D: '7a3d20', F: 'c27709', G: 'f8c12a', H: 'fff6d8', d: '642d18', f: 'f08a1c', g: '5b7381', k: '432115', l: 'e4e8e4', o: '240702', r: 'c9532d' },
    map: [
      '.oooooooooooooooooooo.........................................................................',
      'okDGDDDDGDDDDGDDDDGDDooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo....',
      'okdGddddGddddGddddGddgHHHHHHFHHHHHHHHHHHHHFHHHHHHHHHHHHHFGGGGGGGGGGGGGFGGGGGGGGGGGFGGGGGGHo...',
      'okdGddddGddddGddddGddgGGGGGGFGGGGGGGGGGGGGFGGGGGGGGGGGGGFoooooooooGoooooooooooGoooooooooool...',
      '.ooooooooooooooooooooooooogoooooooooooGoooooooooooooGoooo.........o...........o...........l...',
      '........................ooooo.........o.............o.....................................l...',
      '.......................oGGGGGo............................................................l...',
      '......................oGGGGGGGo...........................................................l...',
      '......................oGGGrGGGo...........................................................l...',
      '......................oGGGGGGGFo..........................................................lo..',
      '......................oGGGGGGGo..........................................................oGfo.',
      '.......................oGGGGGo..........................................................oHfGFo',
      '........................ooooo............................................................oGoo.',
      '..........................................................................................o...',
    ],
  },
  'net-scoop': {
    pal: { M: 'b16f38', S: 'e4e8e4', k: '432115', o: '240702', q: 'ecd585', s: 'b5b9b8', w: 'c98a4b' },
    map: [
      '.................................o..........',
      '.............................oooosoooo......',
      '............................ossssqsssso.....',
      '..........................oosoooq.ooqosoo...',
      '.........................osSoq.q.q.q.qosso..',
      '.........................oso..q...q...qoso..',
      '........................osSq.q.q.q.q.q.qoso.',
      '.oooooooooooooooooooooo.oso.q...q...q...qso.',
      'okkkkwwwwwwwwwwwwwwwwwwoosoq.q.q.q.q.q.qoso.',
      'okkkkMMMMMMMMMMMMMMMMMMosoq...q...q...q..oso',
      '.oooooooooooooooooooooo.osoq.q.q.q.q.q.qoso.',
      '........................oso.q...q...q...qso.',
      '........................osoq.q.q.q.q.q.qoso.',
      '.........................oso..q...q...qoso..',
      '.........................ossoq.q.q.q.qosso..',
      '..........................oosoooq.ooqosoo...',
      '............................ossssqsssso.....',
      '.............................oooosoooo......',
      '.................................o..........',
    ],
  },
  'net-cast': {
    pal: { C: 'ecd585', Y: 'a8862e', g: '5b7381', o: '240702', q: 'ecd585', s: 'b5b9b8' },
    map: [
      '........................o.......................',
      '......................ooCoo.....................',
      '.....................oCCoCCo....................',
      '.....................oCo.oCo....................',
      '....................oCo...oCo...................',
      '.....................oCo.oCo....................',
      '.....................oCCoCCo....................',
      '.....................oooCooo....................',
      '....................oYYYCYYYo...................',
      '...................oYqoooooqYo..................',
      '...................oYoq...qoYo..................',
      '..................oYo..q.q..oYo.................',
      '..................oYo...q...oYo.................',
      '.................oYq...q.q...qYo................',
      '................oYo.q.q...q.q.oYo...............',
      '................oYo..q.....q..oYo...............',
      '...............oYo..q.q...q.q..oYo..............',
      '..............oYoq.q...q.q...q.qoYo.............',
      '..............oYo.q.....q.....q.oYo.............',
      '.............oYo.q.q...q.q...q.q.oYo............',
      '.............oYoq...q.q...q.q...qoYo............',
      '............oYoq.....q.....q.....qoYo...........',
      '...........oYoq.q...q.q...q.q...q.qoYo..........',
      '...........oYq...q.q...q.q...q.q...qYo..........',
      '..........oYq.....q.....q.....q.....qYo.........',
      '.........oYq.q...q.q...q.q...q.q...q.qYo........',
      '.........oYo..q.q...q.q...q.q...q.q..oYo........',
      '........oYo....q.....q.....q.....q....oYo.......',
      '........oYq...q.q...q.q...q.q...q.q...qYo.......',
      '.......oYo.q.q...q.q...q.q...q.q...q.q.oYo......',
      '......oYo...q.....q.....q.....q.....q...oYo.....',
      '......oYo..q.q...q.q...q.q...q.q...q.q..oYo.....',
      '.....oYoq.q...q.q...q.q...q.q...q.q...q.qoYo....',
      '.....oYo.q.....q.....q.....q.....q.....q..oYo...',
      '....oYo.q.q...q.q...q.q...q.q...q.q...q.q.oYo...',
      '...oYq.q...q.q...q.q...q.q...q.q...q.q...q.qYo..',
      '...oYoq.....q.....q.....q.....q.....q.....qoYo..',
      '..oYoq.q...q.q...q.q...q.q...q.q...q.q...q.qoYo.',
      '.oYoq...q.q...q.q...q.q...q.q...q.q...q.q...qoYo',
      '.oYqoooooqoooooqoooooqoooooqoooooqoooooqoooooqYo',
      'oYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
      '.osgooosgooosgooosgooosgooosgooosgooosgooosgoooo',
      '.oggo.oggo.oggo.oggo.oggo.oggo.oggo.oggo.oggo...',
      '..oo...oo...oo...oo...oo...oo...oo...oo...oo....',
    ],
  },
  'net-seine': {
    pal: { G: 'f8c12a', M: 'b16f38', Y: 'a8862e', f: 'f08a1c', g: '5b7381', o: '240702', q: 'ecd585', s: 'b5b9b8', w: 'c98a4b' },
    map: [
      '.oo........................................................................................oo.',
      'owMo......................................................................................owMo',
      'owMo...ooooo......ooooo......ooooo......ooooo......ooooo......ooooo......ooooo............owMo',
      'owMoooofGfffoooooofGfffoooooofGfffoooooofGfffoooooofGfffoooooofGfffoooooofGfffooooooooooooowMo',
      'owMYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYfffffYYYYYYYYYYYYYwMo',
      'owMooqofffffoooooqfffffqooooofffffoqoooofffffooqooofffffoooqoofffffooooqofffffoooooqoooooqowMo',
      'owMoq.qoooqoq...q.qoooq.q...qoqoooq.q...qoqoo.q.q..oqoqo..q.q.ooqoq...q.qoooqoq...q.q...q.owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMo....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q...owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMoq.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.owMo',
      'owMo.q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....qowMo',
      'owMoq.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMo....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q.....q...owMo',
      'owMo...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q..owMo',
      'owMoq.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.q...q.owMo',
      'owMooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqoooooqowMo',
      'owMYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYwMo',
      'owMoooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoooooosgoowMo',
      'owMo..oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggo....oggoowMo',
      '.oo....oo......oo......oo......oo......oo......oo......oo......oo......oo......oo......oo..oo.',
    ],
  },
  'axe': {
    pal: { D: '7a3d20', M: 'b16f38', S: 'e4e8e4', X: '3a3a44', d: '642d18', g: '5b7381', m: '975220', o: '240702', s: 'b5b9b8', w: 'c98a4b', z: '6a6a78' },
    map: [
      '..............................ooooooo....',
      '.............................ossssssso...',
      '.............................ozszzzzXo...',
      '.ooo.........................ozszzzzXo...',
      'oDMwoooooooooooooooooooooooooozszzzzXo...',
      'oDmmwwdDDdDDdDwwwwwwwwwwwwwwwwzszzzzXwo..',
      'oDmmMMDDdDDdDDMMMMMMMMMMMMMMMMzszzzzXwo..',
      'oDmmmmDdDDdDDdmmmmmmmmmmmmmmmmzszzzzXmo..',
      'oDmmoooooooooooooooooooooooooozszzzzXo...',
      '.ooo........................ogsgggggggo..',
      '...........................ogsggggggggo..',
      '.........................oogsggggggggggo.',
      '........................oggggggggggggggo.',
      '.......................osgggggggggggggggo',
      '.......................oSssgggggggggggsso',
      '........................oSSsssssssssssSSo',
      '.........................ooSSSSSSSSSSSoo.',
      '...........................ooooooooooo...',
    ],
  },
  'bucket': {
    pal: { D: '44474e', G: 'c98a4b', L: 'c6d1cc', M: '7a4a28', S: 'e4e8e4', b: '2682b5', d: '606268', h: '94d6f1', i: '1f5f88', k: '32343a', m: 'a5aeb2', n: '8e969a', o: '240702', s: 'b5b9b8', w: '3f7fae', z: '6a6a78' },
    map: [
      '...........................oooooooooooooooo...........................',
      '..........................oMMMMMMMMMMMMMMMMo..........................',
      '........................oooGGGGGGGGGGGGGGGGooo........................',
      '......................oosssMMMMMMMMMMMMMMMMsssoo......................',
      '...................ooosszzzzzoooooooooooozzzzzssooo...................',
      '.................oossszzzoooo............oooozzzsssoo.................',
      '................osszzzooo....................ooozzzsso................',
      '..............ooszzzoo..........................oozzzsoo..............',
      '.............osszzoo..............................oozzsso.............',
      '............oszzoo..................................oozzso............',
      '..........ooszzo......................................ozzsoo..........',
      '.........osszzo........................................ozzsso.........',
      '........oszzoo..........................................oozzso........',
      '........ozzo..............................................ozzo........',
      '.......oszo................................................ozso.......',
      '......oszo..................................................ozso......',
      '.....oszzo..................................................ozzso.....',
      '.....ozzo....................................................ozzo.....',
      '....oszo......................................................ozso....',
      '...oszo........................................................ozso...',
      '...ozzo........................................................ozzo...',
      '..oszo..........................................................ozso..',
      '..ozzo..................ooooooooooooooooooooo...................ozzo..',
      '..ozo...........ooooooooSSSSSSSSSSSSSSSSSLLLLoooooooo............ozo..',
      '.oszo.......ooooSSSSSSSSSSSSSSSSSSSSSSSSSLLLLLLLLLLLLoooo........ozso.',
      '.ozzo...ooooSSSSSSSiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLLLLLLLoooo....ozzo.',
      '.ozo..ooSSSSSiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLLLLLoo...ozo.',
      '.ozo.oSSSiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLLLo..ozo.',
      'oszooSSwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwLLo.ozso',
      'ozzoSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbLLoozzo',
      'ozoSSSbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbhhhhhbbbbbbbbbbbbbbbbbLLLoozo',
      'oznnnnbbbbbbbbbbbbbhhhhhhbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbnndddzo',
      'oznnnnnnbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbnnnndddzo',
      'oznknnnnnnbbbbbbbbbbbbbbbbbbbhhhhbbbbbbbbbbbbbhhhbbbbbbbbbbnnnnnDdkdzo',
      'oznnnmnnnnnnnnbbbbbbbbbbhhbbbbbbbbbbbbbbbbbbbbbbbbbbbbbnnnnnnnnDDdddzo',
      '.onnnmmmnnnnnnnnnnnnnbbbbbbbbbbbbbbbbbbbbbbbbbbbnnnnnnnnnnnnnDDDDdddo.',
      '.onnnmmmmmLLnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnDDDDDDDDdddo.',
      '.onnnmmmmmLLLLLLnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnndddDDDDDDDDDdddo.',
      '..ooommmmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnnnnnnnndddddddddddDDDDDDDDoooo..',
      '....oSmmmmmLLLLLLLLLSSSSSnnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDno.....',
      '....okSSSSSSSLLLLLLLSSSSSnnnnnnnnnnnnnnnnnddddddddddddddnnnnnnnko.....',
      '....ozkkkkkkkSSSSSSSSSSSSSSSSSSSSSnnnnnnnnnnnnnnnnnnnnnnkkkkkkkzo.....',
      '....omzzzzzzzkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkzzzzzzzDo.....',
      '....ommmmmmLLzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzDDDDDDDDo.....',
      '....ommmmmmLLLLLLLLLLSSSSnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDDo.....',
      '.....ommmmmLLLLLLLLLLSSSSnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDo......',
      '.....ommmmmLLLLLLLLLLSSSSnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDo......',
      '.....ommmmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDo......',
      '.....ommmmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDo......',
      '.....ommmmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDo......',
      '.....ommmmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDo......',
      '.....ommmmmmLLLLLLLLLSSSSSnnnnnnnnnnnnnnnddddddddddddddDDDDDDDDo......',
      '......ommmmmLLLLLLLLLSSSSSnnnnnnnnnnnnnnnddddddddddddddDDDDDDDo.......',
      '......ommmmmLLLLLLLLLSSSSSnnnnnnnnnnnnnnnddddddddddddddDDDDDDDo.......',
      '......ommmmmLLLLLLLLLSSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDDo.......',
      '......ommmmmLLLLLLLLLSSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDDo.......',
      '......ommmmmmLLLLLLLLSSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDDo.......',
      '......ommmmmmLLLLLLLLSSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDDo.......',
      '......ommmmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDDo.......',
      '.......ommmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDo........',
      '.......ommmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDo........',
      '.......ommmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDo........',
      '.......ommmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnndddddddddddddDDDDDDDo........',
      '.......ommmmmLLLLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddDDDDDDDDo........',
      '.......ommmmmmLLLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddDDDDDDDDo........',
      '.......ommmmmmLLLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddDDDDDDDDo........',
      '........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddDDDDDDDo.........',
      '........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddDDDDDDDo.........',
      '........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddDDDDDDDo.........',
      '........oSmmmmLLLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddDDDDDDno.........',
      '........okSSSSSSLLLLLLSSSSnnnnnnnnnnnnnnnddddddddddddnnnnnnko.........',
      '........ozkkkkkkSSSSSSSSSSSSSSSSSSnnnnnnnnnnnnnnnnnnnkkkkkkzo.........',
      '........omzzzzzzkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkzzzzzzDo.........',
      '.........ommmmmLzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzDDDDDDo..........',
      '.........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnddddddddddddDDDDDDDo..........',
      '.........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnddddddddddddDDDDDDDo..........',
      '.........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnddddddddddddDDDDDDDo..........',
      '.........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnddddddddddddDDDDDDDo..........',
      '.........ommmmmLLLLLLLLSSSSnnnnnnnnnnnnnddddddddddddDDDDDDDo..........',
      '.........oddddddddddddddddddddddddddddddddddddddddddDDDDDDDo..........',
      '..........odddddddddddddddddddddddddddddddddddddddddDDDDDDo...........',
      '...........oodddddddddddddddddddddddddddddddddddddddDDDDoo............',
      '.............oodddddddddddddddddddddddddddddddddddddDDoo..............',
      '...............ooooodddddddddddddddddddddddddddddooooo................',
      '....................oooooooooooooodoooooooooooooo.....................',
      '..................................o...................................',
    ],
  },
  'lamp': {
    pal: { G: 'f8c12a', H: 'fff6d8', X: '3a3a44', a: 'e9d79a', f: 'f08a1c', o: '240702', s: 'b5b9b8', z: '6a6a78' },
    map: [
      '.....oooo.....',
      '....oo..oo....',
      '...oo....oo...',
      '...o......o...',
      '...o.oooo.o...',
      '...oozzzzoo...',
      '..ozzsszzzzo..',
      '..oXXXXXXXXo..',
      '...oaaaaaao...',
      '..oaaaHHaaao..',
      '..oaaHGGHaao..',
      '..oaaHGGHaao..',
      '..oaHGffGHao..',
      '..oaHGffGHao..',
      '..oaaGffGaao..',
      '..oaaaXXaaao..',
      '...oaaXXaao...',
      '..oXXXXXXXXo..',
      '.ozzsszzzzzzo.',
      '.ozzzzzzzzzXo.',
      '.oXXXXXXXXXXo.',
      '..oooooooooo..',
    ],
  },
  'worms': {
    pal: { C: 'ecd585', E: '8a9a3c', P: 'b85a6a', S: 'e4e8e4', X: '3a3a44', d: '642d18', e: '4c6b2a', g: '5b7381', k: '432115', o: '240702', p: 'e88a8a', s: 'b5b9b8' },
    map: [
      '...........o....',
      '......oo..oPo...',
      '.....oppo..opo..',
      '....opooPo.opo..',
      '....opo.o.opo...',
      '...oopoooopoo...',
      '..oddddddddddo..',
      '.okkkkkkkkkkkko.',
      'osssssssssssssso',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      'oeeeeeeeeeeeeeeo',
      'oEEEEEEEEEEEEEEo',
      'oEEEEECECECEEEEo',
      'oEEEEEEEEEEEEEEo',
      'oeeeeeeeeeeeeeeo',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      'ogsSgggggggggXgo',
      '.oooooooooooooo.',
    ],
  },
  'floats': {
    pal: { B: '3f6f9a', G: 'f8c12a', H: 'fff6d8', M: 'b16f38', a: '94d6f1', o: '240702', r: 'c9532d', t: 'f4e3c1' },
    map: [
      '..o..........',
      '.oro.........',
      '.oro.........',
      '.oro.....o...',
      '.oro....oGo..',
      '.orro...oGo..',
      'orrrro..oGo..',
      'orHrro..oGo..',
      'otttto..oBBo.',
      'otttto.oBBBBo',
      'otttto.oBaBBo',
      'otttto.otttto',
      'otttto.otttto',
      '.otto..otttto',
      '.oMo...otttto',
      '.oMo...otttto',
      '.oMo....otto.',
      '.oMo....oMo..',
      '..o.....oMo..',
      '........oMo..',
      '........oMo..',
      '.........o...',
    ],
  },
  'fish': {
    pal: { o: '240702', e: '0d0502', B: '5b7381', S: 'b5b9b8', W: 'e4e8e4', F: '8f97a3' },
    map: [
      '......oooooo........',
      '....ooBBBBBBoo....oo',
      '..ooBBBBBBBBBBoo.oFo',
      '.oSSBBBBBBBBBBBSooFo',
      'oSeSSSSSSSSSSSSSSFFo',
      'oSSSSSSSSSSSSSSSoFFo',
      '.oWWWWWWWWWWWWWoo.Fo',
      '..ooooWWWWWWoooo..oo',
      '......oooooo........',
    ],
  },
  'fish-fried': {
    pal: { o: '240702', e: '0d0502', B: '7a3d1a', S: 'b8692e', W: 'dfa154', F: '8a4a1e', g: '4a2410' },
    map: [
      '......oooooo........',
      '....oogBBBgBoo....oo',
      '..ooBBgBBBgBBBoo.oFo',
      '.oSSBBgBBBgBBBgSooFo',
      'oSeSSSgSSSgSSSgSSFFo',
      'oSSSSSgSSSgSSSgSoFFo',
      '.oWWWWgWWWgWWWgoo.Fo',
      '..oooogWWWgWoooo..oo',
      '......oooooo........',
    ],
  },
};

const sprites = new Map<string, HTMLCanvasElement>();
// Рыба из ведра рисуется спрайтом своего вида (fish — его id), как в панели ведра; жареная — подрумяненная, с тёмными
// полосками от углей. Без вида — общая картинка из ITEM_ART.
function fishPixels(id: string | undefined, fried: boolean): { w: number; h: number; data: Uint8ClampedArray } | null {
  const sp = id ? FISH.byId[id] : undefined; if (!sp) return null;
  const s = FISH.sprite(sp);
  if (fried) for (let i = 0; i < s.w * s.h; i++) {
    const o = i * 4; if (!s.data[o + 3]) continue;
    const lum = (0.299 * s.data[o]! + 0.587 * s.data[o + 1]! + 0.114 * s.data[o + 2]!) / 255;
    if (lum < 0.12) continue;                                   // контур и глаз остаются
    const k = (i % s.w) % 4 === 1 ? 0.45 : 0.7 + lum * 0.45;    // полоски от решётки
    s.data[o] = 205 * k; s.data[o + 1] = 120 * k; s.data[o + 2] = 52 * k;
  }
  return s;
}
// Картинка вещи на отдельном холсте (собирается один раз); rot — повёрнутая, fish — вид рыбы у рыбы из ведра.
export function itemSprite(kind: ItemKind, rot = false, fish?: string): HTMLCanvasElement {
  const fishy = ITEMS.isFish(kind) && fish && FISH.byId[fish] ? fish : undefined;
  const key = kind + (fishy ? ':' + fishy : '') + (rot ? '+' : '');
  let c = sprites.get(key);
  if (c) return c;
  const px = fishPixels(fishy, kind === 'fish-fried');
  const { pal, map } = ITEM_ART[kind], h = px ? px.h : map.length, w = px ? px.w : map[0]!.length;
  // цвет пикселя (i, y) картинки как она нарисована; null — пусто
  const at = (i: number, y: number): [number, number, number] | null => {
    if (px) { const o = (y * w + i) * 4; return px.data[o + 3] ? [px.data[o]!, px.data[o + 1]!, px.data[o + 2]!] : null; }
    const ch = map[y]![i]!; if (ch === '.') return null;
    const hex = pal[ch] || 'ff00ff';
    return [parseInt(hex.slice(0, 2), 16), parseInt(hex.slice(2, 4), 16), parseInt(hex.slice(4, 6), 16)];
  };
  c = document.createElement('canvas');
  c.width = rot ? h : w; c.height = rot ? w : h;
  const x = c.getContext('2d')!, img = x.createImageData(c.width, c.height);
  for (let y = 0; y < h; y++) for (let i = 0; i < w; i++) {
    const rgb = at(i, y); if (!rgb) continue;
    const pxl = rot ? h - 1 - y : i, pyl = rot ? i : y, o = (pyl * c.width + pxl) * 4;
    img.data[o] = rgb[0]; img.data[o + 1] = rgb[1]; img.data[o + 2] = rgb[2]; img.data[o + 3] = 255;
  }
  x.putImageData(img, 0, 0);
  sprites.set(key, c);
  return c;
}
